// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8DabopnXatf-XMYEANZGLVVDIcvusU8M',
    appId: '1:915601686359:web:2865ffcc6d8791af880812',
    messagingSenderId: '915601686359',
    projectId: 'myworkers-1b088',
    authDomain: 'myworkers-1b088.firebaseapp.com',
    storageBucket: 'myworkers-1b088.firebasestorage.app',
    measurementId: 'G-1QGS9TXBFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK8yLcWALE0V-V2Jw87vrB_fSQbQUT2cY',
    appId: '1:915601686359:android:aad301ad1c3088d9880812',
    messagingSenderId: '915601686359',
    projectId: 'myworkers-1b088',
    storageBucket: 'myworkers-1b088.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPeEYwp6b_p1gsCeXdOsT7S7SS5y4swU4',
    appId: '1:915601686359:ios:f5e9894eae723883880812',
    messagingSenderId: '915601686359',
    projectId: 'myworkers-1b088',
    storageBucket: 'myworkers-1b088.firebasestorage.app',
    iosClientId: '915601686359-v6plrh0pam9brg1o39lorlaqjkj8chh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myworkers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPeEYwp6b_p1gsCeXdOsT7S7SS5y4swU4',
    appId: '1:915601686359:ios:f5e9894eae723883880812',
    messagingSenderId: '915601686359',
    projectId: 'myworkers-1b088',
    storageBucket: 'myworkers-1b088.firebasestorage.app',
    iosClientId: '915601686359-v6plrh0pam9brg1o39lorlaqjkj8chh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myworkers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8DabopnXatf-XMYEANZGLVVDIcvusU8M',
    appId: '1:915601686359:web:42927a505829b3b6880812',
    messagingSenderId: '915601686359',
    projectId: 'myworkers-1b088',
    authDomain: 'myworkers-1b088.firebaseapp.com',
    storageBucket: 'myworkers-1b088.firebasestorage.app',
    measurementId: 'G-WL0GGBMPCZ',
  );
}
