arb-dir: lib/core/l10n/arb
template-arb-file: it.arb
output-localization-file: core_localizations.dart
nullable-getter: false
output-class: CoreLocalizations
synthetic-package: false
untranslated-messages-file: untranslated_messages.json